Model_Parameters:
  Site: 'Nebraska'
  Experiment: '0'
  agents:
    Rattlesnake: 1

Landscape_Parameters:
  Thermal_Database_fp: '/home/micha/Documents/suffugium/environment_data/Nebraska_cleaned.csv'
  ENV_Temperature_Cols:
    Open: 'Open'
    Burrow: 'Burrow'

Rattlesnake_Parameters:
  species: 'Rattlesnake'
  body_size_config:
    distribution: 'normal'
    mean: 258.1
    std: 86.6
    min: 122
    max: 575
  active_hours: [17, 18,19,20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  Initial_Body_Temperature: 25
  initial_calories: 100
  utility:
    max_meals: 3
  thermal_preference:
    k: 0.01
    t_pref_min: 19
    t_pref_max: 32
    t_opt: 29
  voluntary_ct:
    min_temp: 5
    max_temp: 45
    max_steps: 2
  strike_performance: 0.22
  delta_t: 60
  smr:
    X1_mass: 0.93
    X2_temp: 0.044
    X3_const: -2.58
  Brumation:
    file_path: '/home/micha/Documents/suffugium/brumation_files/brumation_dates_Nebraska_0.json'
    scale: 'Day'
    temperature: 10
  behavior_activity_coefficients: {'Rest':1,
                                   'Thermoregulate':1.5,
                                   'Forage':1.5,
                                   'Search':1.5,
                                   'Brumation':1}

Interaction_Parameters:
  calories_per_gram: 1.38
  digestion_efficiency: 0.8
  expected_prey_body_size: 65
  handling_time: 2
  attack_rate_range: 
    min: 0.001
    max: 0.01
  prey_density_range:
    min: 1
    max: 22
  searching_behavior: True
  prey_active_hours: [20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6]
